### ISSUE TITLE
Ball covariance not used in `TeamData`

### ISSUE THREAD

**Issue by jaagut** [bit-bots/humanoid_league_misc#141]
https://github.com/bit-bots/humanoid_league_misc/blob/db2d271a258c3416a9914cadb4565e7512d18aae/humanoid_league_team_communication/humanoid_league_team_communication/converter/message_to_team_data_converter.py#L70

The results of `convert_to_row_major_covariance` should probably be put into `ball` and not be forgotten?

**Comment by Flova** [comment]
They are updated. The covariance matrix of the first argument is passed by reference and modified accordingly using the data in the second argument.
