### ISSUE TITLE
Game controller does not publish /wifi_connected message

### ISSUE THREAD

**Issue by JanGut** [bit-bots/humanoid_league_misc#24]
The body behavior subscribes to the `/wifi_connected std_msgs/bool.msg`, but the game controller does not publish this.

**Comment by TanjaSmiley** [comment]
The body behavior subscribes to this topic only in the script `penalty_behaviour.py`. This is not used anymore as the penalty kick behavior is directly integrated in the DSD. Therefore it is not necessary to publish this information through the game controller node.

**Comment by ftsell** [comment]
In my oppinion (and @SammyRamone 's too) the game controller should rather publish a `/game_controller_connected` message because that is the info we really want
