### ISSUE TITLE
Transformer publishes no GoalRelative message

### ISSUE THREAD

**Issue by jaagut** [bit-bots/humanoid_league_misc#26]
Correct me if I'm wrong...
Since we have switched to the `GoalPartsInImage` message, the transformer does not publish `GoalRelative` anymore. But information of the goal parts could also be relevant for the `GoalRelative` message, which is e.g. (kind of) used in team communication. So team communication gets no data anymore.

**Comment by timonegk** [comment]
Is this still relevant @NFiedler @jgueldenstein?

**Comment by NFiedler** [comment]
Team Communication as well as the TeamData message have to be adapted to the NuBots protocol. This should be fixed as well.

**Comment by JanGut** [comment]
So TODO instead of NiceToHave?

**Comment by Flova** [comment]
I think this issue is deprecated after the hlm refactoring.
