### ISSUE TITLE
Adapt to TeamData message

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/humanoid_league_misc#3]
The TeamData message has an [issue](https://github.com/bit-bots/humanoid_league_msgs/issues/7) with associating detections to robots. We need to implement the proposed workaround here to be able to properly work with it.

**Comment by TanjaSmiley** [comment]
Workaround is merged, but this has to be refactored after the season

**Comment by NFiedler** [comment]
#6 basically includes the refactoring part, I think. So I will close this now.
