### ISSUE TITLE
Transformer: Transform image mask to point cloud

### ISSUE THREAD

**Issue by jaagut** [bit-bots/humanoid_league_misc#38]
## Is your feature request related to a problem? Please describe.
Currently, only line points can be transformed. But line points generate additional overhead in the vision and carry less information than a line mask image. Also the line points message is not optimal.

## Describe the solution you'd like
I suggest, supporting the transform of mask images into point cloud to reduce the overhead and provide more line information for the localization.

## Describe alternatives you've considered
Alternatively, the image mask could be transformed into a perspectively warped image, but this is harder for the localization to use.

**Comment by timonegk** [comment]
It might be a good idea to do that in a C++ python module
