### ISSUE TITLE
humanoid_league_transform: error message when empty camera info is received

### ISSUE THREAD

**Issue by timonegk** [bit-bots/humanoid_league_misc#9]

**Comment by NFiedler** [comment]
How would you describe an empty camera info message?

**Comment by timonegk** [comment]
Every value outside of the header is zero. It happens when the image provider is started with a missing camera info file

**Comment by jgueldenstein** [comment]
This is solved similar to the implementation in the ros [image processing](https://github.com/ros-perception/image_pipeline/blob/8d01c930e66bdeb58c4b138539a64ddea0b17e10/image_proc/src/nodelets/rectify.cpp#L117)

in bb143a7562342533ee548c21c30c70b53133db76
