### ISSUE TITLE
Team comm: Handle messages without extension

### ISSUE THREAD

**Issue by jaagut** [bit-bots/humanoid_league_misc#93]
## Is your feature request related to a problem? Please describe.
Currently, the team comm only handles our custom protobuf message `robocup_extension_pb2.Message()`.
We should also be able to handle the default `robocup_pb2.Message()`.
This is especially relevant for DropIn games.

**Comment by texhnolyze** [comment]
As far as I've read up on Protobuf our extended Msgs should be interchangeable with the base messages, as they are only an extension and will lead to the extra fields just not being parsed, when they are not available.
We just need to make sure, that all our extra fields are always optional.
